on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  run_if:
    if: startsWith(github.head_ref, 'release-pr/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: regular-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-release
      - name: Release
        run: cargo release --no-tag --no-push
      - name: Extract version
        id: extract_version
        run: |
          echo "VERSION=$(echo ${{ github.event.pull_request.title }} | perl -0777 -pe 's/^release: //')" >> $GITHUB_OUTPUT
      - name: Push tag
        env:
          VERSION: ${{ steps.extract_version.outputs.VERSION }}
        run: |
          echo "Version is $VERSION"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a $VERSION -m "Release $VERSION"
          git push origin tag $VERSION

